# Travis CI script
# This is a skeleton created by zproject.
# You can add hand-written code here.
# Note: Heavily modified

language: c

cache: ccache

os:
- linux

sudo: false

services:
- docker

# Set CI_TIME=true to enable build-step profiling in Travis
# Set CI_TRACE=true to enable shell script tracing in Travis
# Set CI_CONFIG_QUIET=true to enable "configure --quiet" (only report stderr)
env:
  global:
    - CI_TIME=false
    - CI_TRACE=false
    - CI_QUIET=true
  matrix:
    - BUILD_TYPE=default CI_CZMQ_VER=4
    - BUILD_TYPE=default CI_CZMQ_VER=3
    - BUILD_TYPE=default-Werror
#   - BUILD_TYPE=cmake
#   - BUILD_TYPE=android
#   - BUILD_TYPE=check-py

matrix:
  include:
  - env: BUILD_TYPE=valgrind CI_CZMQ_VER=3
    os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - valgrind
        - apport
  - env: BUILD_TYPE=valgrind CI_CZMQ_VER=4
    os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - valgrind
        - git
        - apport
#        - asciidoc
#        - xmlto

addons:
  sources:
  - sourceline: 'deb http://download.opensuse.org/repositories/home:/zeromq:/git-draft/xUbuntu_12.04/ ./'
    key_url: 'http://download.opensuse.org/repositories/home:/zeromq:/git-draft/xUbuntu_12.04/Release.key'
  apt:
    packages:
    - asciidoc
    - xmlto
#    - libzmq3-dev
#    - libczmq-dev
#    - libmlm-dev
#    - libfty-proto-dev
    - git
    - apport
    - valgrind

# some core file info
before_install:
- ulimit -c
- ulimit -a -S
- ulimit -a -H
- cat /proc/sys/kernel/core_pattern
- if [ $TRAVIS_OS_NAME == "osx" ] ; then brew update; brew install binutils valgrind ; fi

# install gdb
install:
- sudo apt-get install -y gdb  

# enable core dumps with unlimited size
before_script:
- ulimit -c unlimited -S  

# Hand off to generated script for each BUILD_TYPE
script: ./ci_build.sh

# print core file content
after_failure:
- COREFILE=$(find . -maxdepth 10 -name "core*" | head -n 1) 
- if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" example -ex "thread apply all bt" -ex "set pagination 0" -batch; fi

before_deploy: . ./ci_deploy.sh
deploy:
  provider: releases
  api_key:
    # To encrypt your access token run: `travis encrypt -r user/repo`
    secure: <encrypted github access token>
  file_glob: true
  file: ${FTY_METRIC_CACHE_DEPLOYMENT}
  skip_cleanup: true
  on:
    branch: master
    tags: true
    condition: $TRAVIS_OS_NAME =~ (linux) && $BUILD_TYPE =~ (default)
